config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home", to: "static_pages#home", as: "home"
  get "static_pages/season_show/:season/:serie", to: "static_pages#season_show", as: "season_show"
  get "static_pages/episode_show/:episode_id", to: "static_pages#episode_show", as: "episode_show"
  get "static_pages/character_show/:character_name", to: "static_pages#character_show", as: "character_show", constraints: { character_name: /[^\/]+/ }
  post "static_pages", to: "static_pages#character_search", as: "character_search"
  get "static_pages/search_results/:character_input", to: "static_pages#search_results", as: "search_results", constraints: { character_input: /[^\/]+/ }

  root to: "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  @@base_url = 'https://tarea-1-breaking-bad.herokuapp.com/api/'
  def home
    response = RestClient.get(@@base_url + 'episodes?series=Breaking+Bad')
    bb_episodes = JSON.parse(response.to_str)
    response = RestClient.get(@@base_url + 'episodes?series=Better+Call+Saul')
    bcs_episodes = JSON.parse(response.to_str)
    seasons = {bb: [], bcs: []}
    bb_episodes.each do |epi|
      if !seasons[:bb].include? epi["season"].to_i
        seasons[:bb] << epi["season"].to_i
      end
    end
    bcs_episodes.each do |epi|
      if !seasons[:bcs].include? epi["season"].to_i
        seasons[:bcs] << epi["season"].to_i
      end
    end
    @results = seasons
  end

  def season_show
    season = params[:season]
    serie = params[:serie]
    if serie == "bb"
      serie_name = "Breaking+Bad"
      @nombre_serie = "Breaking Bad"
    elsif serie == "bcs"
      serie_name = "Better+Call+Saul"
      @nombre_serie = "Better Call Saul"
    end
    response = RestClient.get(@@base_url + "episodes?series=#{serie_name}")
    episodes = JSON.parse(response.to_str)
    season_episodes = []
    episodes.each do |epi|
      if epi["season"] == season
        season_episodes << epi
      end
    end
    @results = season_episodes
    @serie_id = serie
    @season = season
  end

  def episode_show
    episode_id = params[:episode_id]
    response = RestClient.get(@@base_url + "episodes/#{episode_id}")
    episodes = JSON.parse(response.to_str)
    @results = episodes[0]
    if episodes[0]["series"] == "Breaking Bad"
      @image_path = "/fotos/Breaking_Bad_logo.png"
    else
      @image_path = "/fotos/BCS_logo.png"
    end
  end

  def character_show
    character_name = params[:character_name]
    response = RestClient.get(@@base_url + "characters?name=#{character_name}")
    characters = JSON.parse(response.to_str)
    @results = characters[0]
    response = RestClient.get(@@base_url + "quote?author=#{character_name}")
    @quotes = JSON.parse(response.to_str)
  end

  def character_search
    character_input = params[:character_input]
    redirect_to search_results_path(character_input)
  end

  def search_results
    @character_input = params[:character_input]
    respuestas = RestClient.get(@@base_url + "characters?name=#{@character_input}")
    respuestas = JSON.parse(respuestas.to_str)
    response = []
    response += respuestas
    pag = 1
    until respuestas.empty?
      respuestas = RestClient.get(@@base_url + "characters?name=#{@character_input}&limit=10&offset=#{10 * pag}")
      respuestas = JSON.parse(respuestas.to_str)
      response += respuestas
      pag += 1
    end
    @results = response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg my-navbar">
  <%= image_tag "fotos/apinkman.jpg", class: "my-icon align-top" %>
  <%= link_to "API-nkman", home_path, class: "navbar-brand my-navbar-text" %>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Temporadas", home_path, class: "nav-link my-navbar-text" %>
      </li>
    </ul>
  </div>
  <div>
    <%= form_with(method: :post, url: character_search_path) do |form| %>
      <%= form.text_field :character_input, placeholder: "Personaje", class: "form-control-sm" %>
      <%=form.submit 'Buscar', class: "btn btn-sm btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>API-nkman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </head>

  <body class="fondo">
    <%= yield %>
  </body>
</html>

app/views/static_pages/character_show.html.erb
<%= render 'layouts/navbar' %>
<%= link_to "Atrás", :back, class: "btn btn-outline-dark my-back" %>

<div class="container">
  <div class="row">
    <div class="col-3">
      <%= image_tag(@results["img"], :alt => "Foto no disponible", class: "img-thumbnail")%>
    </div>
    <div class="col-9">
      
      <h1><%= @results["name"] %></h1>
      <h2>(aka. <%= @results["nickname"] %>)</h2>
      <br>
      <h5>Actor/a: <%= @results["portrayed"] %></h5>
      <% unless @results["birthday"].nil? %>
        <h5>Nacimiento: <%= @results["birthday"] %></h5>
      <% end %>
      <h5>Ocupaciones:</h5>
      <ul>
        <% @results["occupation"].each do |ocu| %>
        <li><%= ocu %></li>
        <% end %>
      </ul>
      <h5>Estado: <%= @results["status"] %></h5>
    </div>
  </div>
  <hr>
  <br>
  <h2 align="center">Temporadas en las que apareció</h2>
  <br>
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-3">
      <%= image_tag "fotos/Breaking_Bad_logo.png", class: "img-thumbnail" %>
      <% if @results["appearance"].empty? %>
        <p>No se registran apariciones en esta serie.</p>
      <% else %>
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th>Temporadas</th>
            </tr>
          </thead>
          <tbody>
            <% @results["appearance"].each do |season| %>
              <tr>
                <td><%= link_to "Temporada #{season}", season_show_path(season, :bb), class: "my-table-text"%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="col-2">
    </div>
    <div class="col-3">
      <%= image_tag "fotos/BCS_logo.png", class: "img-thumbnail" %>
      <% if @results["better_call_saul_appearance"].empty? %>
        <p>No se registran apariciones en esta serie.</p>
      <% else %>
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th>Temporadas</th>
            </tr>
          </thead>
          <tbody>
            <% @results["better_call_saul_appearance"].each do |season| %>
              <% if season != 0 %>
                <tr>
                  <td><%= link_to "Temporada #{season}", season_show_path(season, :bcs), class: "my-table-text" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="col-2">
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col">
      <h2>Citas:</h2>
      <% if @quotes.empty? %>
        <p>No se registran citas para este personaje.</p>
      <% else %>
        <ul>
          <% @quotes.each do |quote| %>
            <li><%= "#{quote['quote']} (#{quote['series']})" %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/episode_show.html.erb
<%= render 'layouts/navbar' %>
<%= link_to "Atrás", :back, class: "btn btn-outline-dark my-back" %>

<div class="container">
  <div class="row">
    <div class="col-3">
      <%= image_tag @image_path, class: "img-thumbnail" %>
    </div>
    <div class="col-9">
      <h1><%= @results["title"] %></h1>
      <h2>Temporada <%= @results["season"] %> | Episodio <%= @results["episode"] %></h2>
      <h5>Estreno: <%= @results["air_date"].to_date %></h5>
    </div>
  </div>
  <br>
  <h4>Personajes en este episodio</h4>
  <div class="row">
      
    <% @results["characters"].each do |person| %>
      <div class="col-3">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= person %></h5>
            <%= link_to "Información", character_show_path(person), class: "btn btn-success" %>
          </div>
        </div>        
      </div>
    <% end %>
      
  </div>
</div>

app/views/static_pages/home.html.erb
<%= render 'layouts/navbar' %>
<br>
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Temporadas</h1>
      <p>A continuación puedes revisar las temporadas de ambas series y seleccionar alguna para ver el detalle.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <div class="row">
        <div class="col">
          <div class="card" style="width: 18rem;">
            <%= image_tag "fotos/BB.jpg", class: "card-img-top" %>
            <div class="card-body">
              <p class="card-text">Tras cumplir 50 años, Walter White, un profesor de química de un instituto de Albuquerque, Nuevo México, se entera de que tiene un cáncer de pulmón incurable. La brutal noticia lo impulsa a dar un drástico cambio a su vida: decide, con la ayuda de un antiguo alumno, fabricar anfetaminas y ponerlas a la venta.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <%= image_tag "fotos/Breaking_Bad_logo.png", class: "img-thumbnail" %>
          
          <table class="table table-striped table-dark">
            <thead>
              <tr>
                <th>Temporadas</th>
              </tr>
            </thead>
            <tbody>
              <% @results[:bb].each do |season| %>
                <tr>
                  <td><%= link_to "Temporada #{season}", season_show_path(season, :bb), class: "my-table-text" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="row">
        <div class="col">
          <div class="card" style="width: 18rem;">
            <%= image_tag "fotos/BCS.png", class: "card-img-top" %>
            <div class="card-body">
              <p class="card-text">Precuela de la serie "Breaking Bad", centrada en el personaje del abogado Saul Goodman, seis años antes de conocer a Walter White. La serie cuenta cómo un picapleitos de poca monta llamado Jimmy McGill, con problemas para llegar a fin de mes, se convierte en el abogado criminalista Saul Goodman.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <%= image_tag "fotos/BCS_logo.png", class: "img-thumbnail" %>
          
          <table class="table table-striped table-dark">
            <thead>
              <tr>
                <th>Temporadas</th>
              </tr>
            </thead>
            <tbody>
              <% @results[:bcs].each do |season| %>
                <tr>
                  <td><%= link_to "Temporada #{season}", season_show_path(season, :bcs), class: "my-table-text" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/search_results.html.erb
<%= render 'layouts/navbar' %>
<%= link_to "Atrás", :back, class: "btn btn-outline-dark my-back" %>

<div class="container">
  <div class="row">
    <div class="col", align="center">
      <h1>Resultados</h1>
      <hr>
      <h4>Buscaste:</h4>
      <h5><%= @character_input %></h5>
      <hr>
    </div>
  </div>
  <div class="row">
    <% @results.each do |character| %>
      <div class="col-3">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= character["name"] %></h5>
            <%= link_to "Información", character_show_path(character["name"]), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>

app/views/static_pages/season_show.html.erb
<%= render 'layouts/navbar' %>
<%= link_to "Atrás", :back, class: "btn btn-outline-dark my-back" %>

<div class="container">
  
  <div class="row">
    <div class="col-sm">
      <h1>Episodios</h1>
      <h2><%= @nombre_serie %> | Temporada <%= @season %></h2>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-4">
      <%= image_tag "#{@serie_id}_S#{3}.jpg", class: "img-thumbnail" %>
    </div>
    <div class="col-8">
      <table class="table table-striped table-dark">
        <thead>
          <tr>
            <th>N°</th>
            <th>Título</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |epi| %>
            <tr>
              <td><%= epi["episode"] %></td>
              <td><%= link_to epi["title"], episode_show_path(epi["episode_id"]), class: "my-table-text" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>